name: Feature request
description: You have an idea for a new feature? Tell us here!
type: feature
body:
  - type: markdown
    attributes:
      value: >-
        ## ✨ First of all: Thank you for choosing Mainsail! ✨

        #### This form is ONLY for feature requests related to Mainsail!

        ---
  - type: textarea
    id: request
    attributes:
      label: 'Requested feature:'
      description: >-
        A clear and concise description of the feature you wish to see implemented.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: 'Solves the following problem:'
      description: |
        Is your feature request related to a problem? Please describe below.
        (In case there is an existing bug report, please add the link to it)
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: 'Additional information:'
      description: |
        If you have any additional information use the field below.
